spring.datasource.url: jdbc:mysql://localhost:3306/sensors_monitor?useSSL=false
spring.datasource.username: root
spring.datasource.password: 11111111
spring.jpa.hibernate.use-new-id-generator-mappings: false


users:
  usersList:
    - login: super
      password: super
      status: ADMIN
    - login: nick
      password: nick
      status: VIEWER